-- Crea la base de datos y la tabla que usa la API 
CREATE DATABASE IF NOT EXISTS crud_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; 
USE crud_db; 
CREATE TABLE IF NOT EXISTS users ( 
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
name VARCHAR(100) NOT NULL, 
email VARCHAR(150) NOT NULL UNIQUE, 
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
); 